name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

      # Set up MongoDB connection string
      - name: Set up MongoDB connection string
        env:
          mongoURI: ${{ secrets.mongoURI }}

      # Run tests
      - name: Run tests
        run: npm test
        env:
          mongoURI: ${{ secrets.mongoURI }}
